#!/usr/bin/env bash
# This script installs nginx on a server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/domain/html
sudo chmod -R 755 /var/www/domain
echo 'Hello World!' > /var/www/domain/html/index.html
sudo echo "server {
        listen 80;
        listen [::]:80;

        root /var/www/domain/html;
        index index.html index.htm index.nginx-debian.html;

        server_name domain http://efezinoidisi.tech;

        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-available/domain
sudo ln -s /etc/nginx/sites-available/domain /etc/nginx/sites-enabled/
sudo service nginx start
