#!/usr/bin/env bash
# This script installs nginx web server

sudo apt update
sudo apt -y install nginx
sudo ufw allow "Nginx HTTP"
sudo echo "Hello World!" > /var/www/html/index.html
if [[ $(pgrep nginx) ]]; then
    sudo service nginx restart
else
    sudo service nginx start
fi
