#!/usr/bin/env bash
# This script installs nginx on a server

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
if [[ $(pgrep nginx) ]]; then
    sudo service nginx restart
else
    sudo service nginx start
fi
