#!/usr/bin/env bash
# This script installs nginx web server

sudo apt update
sudo apt -y install nginx
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > sudo tee /var/www/html/index.html
sudo service nginx start
