#!/usr/bin/env bash
# This script installs nginx on a server and redirects

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html

redirect="location \/redirect_me {\n\t\treturn 301 https:\/\/javascript.info;}\n"
sed -i "s/server_name _;/$redirect/" /etc/nginx/sites-available/default

service nginx restart
