#!/usr/bin/env bash
# create backup of mysql databases

password="$1"

mysql -uroot -p"$password" -e "show databases;" | grep -Ev "Database|information_schema|performance_schema|mysql" | xargs mysqldump -uroot -p"$password" --databases > backup.sql

tar -cvzf $(date +%d-%m-%Y).tar.gz backup.sql
