#!/usr/bin/env bash
# make nginx listen on port 80 instead of 8080

sudo rm -rf /etc/nginx/sites-enabled
# create symbolic link from sites-available to sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled
sudo service nginx restart