#!/usr/bin/env bash
# This script is displayingnumbers 1 to 20 10 using while loop

(( i = 1 ))
while ((i <= 20)); do
    echo $i
    case $i in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
    esac
    (( i = i + 1 ))
done
