#!/usr/bin/env bash
# This script enables nginx to run as nginx user

chmod u+rw /etc/nginx/nginx.conf
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

sed -i "s/80/8080/g" /etc/nginx/sites-available/default

sudo service nginx restart
